# Generated by Django 5.0.2 on 2024-04-20 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254xxxxxxxxx' for Kenya. Exactly 12 digits allowed.", regex='^\\+?254\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('nationality', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Non-Kenyan', 'Non-Kenyan')], max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('dependants', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Has_Partner', 'Has_Partner')], max_length=20)),
                ('partner', models.CharField(max_length=3)),
                ('income_status', models.CharField(choices=[('LOW_INCOME', 'LOW_INCOME'), ('MIDDLE_INCOME', 'MIDDLE_INCOME'), ('HIGH_INCOME', 'HIGH_INCOME')], max_length=20)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'EMPLOYED'), ('UNEMPLOYED', 'UNEMPLOYED'), ('SELF_EMPLOYED', 'SELF_EMPLOYED')], max_length=20)),
                ('join_month_year', models.CharField(help_text="Enter in the format 'MM/YYYY'", max_length=7)),
            ],
        ),
    ]
