# Generated by Django 5.0.2 on 2024-04-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_dependants_customer_dependants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.customer'),
        ),
    ]
