# Generated by Django 5.0.2 on 2024-04-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_servicedetails_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHONE_SERVICE_COST', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('LINES_COST_PER_LINE', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('INTERNET_SERVICE_COST', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('ONLINE_SECURITY_COST', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('DEVICE_PROTECTION_COST_PER_DEVICE', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('STREAMING_TV_COST', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('STREAMING_MOVIES_COST', models.DecimalField(decimal_places=2, default=700, max_digits=10)),
                ('ONLINE_BACKUP_COST', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('TECH_SUPPORT_COST', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperlessBilling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('ContractType', models.CharField(choices=[('Month-to-month', 'Month-to-month'), ('One year', 'One year'), ('Two year', 'Two year')], max_length=50)),
                ('PaymentMethod', models.CharField(choices=[('Bank transfer (automatic)', 'Bank transfer (automatic)'), ('Credit card (automatic)', 'Credit card (automatic)'), ('Electronic check', 'Electronic check'), ('Mailed check', 'Mailed check')], max_length=50)),
                ('MonthlyCharges', models.IntegerField(blank=True, null=True)),
                ('TotalCharges', models.IntegerField(blank=True, null=True)),
                ('service_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicedetails')),
            ],
        ),
    ]
