# Generated by Django 5.0.2 on 2024-04-21 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rates_billingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='service_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.servicedetails'),
        ),
    ]
