# Generated by Django 5.0.2 on 2024-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_billingdetails_service_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_service_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('internet_service_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_security_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('device_protection_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('streaming_tv_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('streaming_movies_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_backup_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tech_support_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
